### ISSUE TITLE
Woodland Edge scoring bugs

### ISSUE THREAD

**Issue by Liverbugg** [glaures/forestshuffle#7]
Adding a Squeaker (Woodland Edge) increments the base game Squealer so doesn't count as a Woodland Edge card for the European Wildcat scoring.

The base game Wild Boar (10pts if any Squeakers) is scoring with the new Wild Boar (female) rule (10 x Squeakers).

**Comment by glaures** [comment]
Fixed in 1.5.2

**Comment by Liverbugg** [comment]
The Wild Boar issue is still there.

**Comment by glaures** [comment]
True, apologies. Should be fixed now
