### ISSUE TITLE
Section scoring totals

### ISSUE THREAD

**Issue by Liverbugg** [glaures/forestshuffle#8]
First, let me say thanks for making this, it took scoring the game from being a blocker to get this played in my household to not an issue.

If you add and then remove cards (mistake or just playing around to see how combos could score) the subtotal for each category doesn't always go back down to 0 points.  The top overall total is correct though.

![Screenshot_20240908-071159](https://github.com/user-attachments/assets/ecf39d48-e826-4142-b7a9-a5ebc8d67382)

**Comment by glaures** [comment]
fixed
